name: Pipeline using Docker cloud services

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: mikesir87
  DBC_BUILDER: mikesir87/personal-builder
  IMAGE_NAME: mikesir87/visual-chatbot

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      IMAGE_TAGS: ${{ toJSON( fromJSON(steps.meta.outputs.json).tags ) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up containerd
        uses: docker/setup-docker-action@v4
        with:
          set-host: true
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image tags and labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,enable=true,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: ${{ env.DBC_BUILDER}}

      - id: build
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          sbom: true
          push: true
          load: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign images
        run: |
          cosign sign --yes --recursive ${{ env.IMAGE_NAME }}@${{ steps.build.outputs.imageid }}
      
